In [ ]:
#Горський Володимир. ФІТ 4-5. Варіант 4.

import pandas
import numpy
import numpy as np

#завдання 1. Створіть одновимірний масив (вектор) з непарними числами від 1 до 19 та виведіть його значення.

numbers = np.arange(1, 20, 2)
print("\nЗавдання 1:\n", numbers)

#завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число більше попереднього на 2, та виведіть його значення.
numbers = np.arange(1, 19, 2).reshape(3, 3)
print("\nЗавдання 2:\n", numbers)

#завдання 3. Створіть масив розміром 7x7, заповніть його випадковими цілими числами від -5 до 5 та виведіть його значення.
numbers = np.random.randint(-5, 6, size=(7, 7))
print("\nЗавдання 3:\n", numbers)

#завдання 4. Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть максимальний елемент.
numbers = np.random.rand(6, 6)
max = np.max(numbers)
print("\nЗавдання 4:\n", numbers, "\n Максимальне значення:", max)

#завдання 5. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.
print("\nЗавдання 5:\n")
num1 = np.random.randint(-5, 6, size=4)
num2 = np.random.randint(-5, 6, size=4)
print("Масив 1:", num1)
print("Масив 2:", num2)
sum = num1 + num2
dif = num1 - num2
multiply = num1 * num2
print("Додавання:", sum)
print("Віднімання:", dif)
print("Множення:", multiply)

#завдання 6. Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.
print("\nЗавдання 6:\n")
vector1 = np.random.rand(4)
vector2 = np.random.rand(4)
print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
dot = np.dot(vector1, vector2)
print("Скалярний добуток:", dot)

#завдання 7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
print("\nЗавдання 7:\n")
num1 = np.random.randint(1, 11, size=(2, 3))
num2 = np.random.randint(1, 11, size=(3, 2))
dot = np.dot(num1, num2)
print("Скалярний добуток:\n", dot)

#завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.
print("\nЗавдання 8:\n")
numbers = np.random.randint(1, 16, size=(3, 3))
print("Матриця:\n", numbers)
intnumbers = np.linalg.inv(numbers)
print("Обернена матриця:\n", intnumbers)

#завдання 9. Створіть матрицю розміром 7x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
print("\nЗавдання 9:\n")
numbers = np.random.rand(7, 4)
print("Матриця:\n", numbers)
tnumbers = numbers.T
print("Транспонована матриця:\n", tnumbers)

# завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
print("\nЗавдання 10:\n")
numbers = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4)
print("Матриця:\n", numbers)
print("Вектор:\n", vector)
dob = np.dot(numbers, vector)
print("Добуток матриці на вектор:\n", dob)

# завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю.
print("\nЗавдання 11:\n")
numbers = np.random.rand(2, 3)
vector = np.random.rand(3)
print("Матриця:\n", numbers)
print("Вектор:\n", vector)
dob = np.dot(numbers, vector)
print("Добуток матриці на вектор:\n", dob)

# завдання 12. Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення першої матриці до другої (поелементне ділення).
print("\nЗавдання 12:\n")
numbers1 = np.random.randint(1, 11, size=(5, 5))
numbers2 = np.random.randint(1, 11, size=(5, 5))
print("Матриця 1:\n", numbers1)
print("Матриця 2:\n", numbers2)
vidn = numbers1 / numbers2
print("Відношення матриць:\n", vidn)

# завдання 13. Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму їх елементів.
print("\nЗавдання 13:\n")
numbers1 = np.random.randint(1, 11, size=(5, 5))
numbers2 = np.random.randint(1, 11, size=(5, 5))
print("Матриця 1:\n", numbers1)
print("Матриця 2:\n", numbers2)
sum = np.sum(numbers1 + numbers2)
print("Сума елементів двох матриць:", sum)

# завдання 14. Створіть матрицю розміром 8x8, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть добуток елементів матриці.
print("\nЗавдання 14:\n")
numbers = np.random.randint(1, 101, size=(8, 8))
print("Матриця:\n", numbers)
dob = np.prod(numbers)
print("Добуток елементів матриці:", dob)

# завдання 15. Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє арифметичне значення елементів кожного рядка матриці.
print("\nЗавдання 15:\n")
numbers = np.random.uniform(-2, 2, size=(6, 6))
print("Матриця:\n", numbers)
average = np.mean(numbers, axis=1).reshape(6, 1)
print("Вектор-стовпчик середніх значень:\n", average)



Завдання 1:
 [ 1  3  5  7  9 11 13 15 17 19]

Завдання 2:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]

Завдання 3:
 [[-1  3  2 -4  2  0 -2]
 [ 3 -4 -5 -2 -2  5 -3]
 [-3 -3 -3  2  3  1 -3]
 [-5 -4 -3 -3 -4 -3  2]
 [ 1  4  3  1 -2 -5 -4]
 [-5  5 -1  0 -1  0 -2]
 [ 3 -1  0  0  3  0  5]]

Завдання 4:
 [[0.52454351 0.38953864 0.74053954 0.24412591 0.46217441 0.92653087]
 [0.24069681 0.24481627 0.76695797 0.67971758 0.14693942 0.60865574]
 [0.00495031 0.87034754 0.26069435 0.52152146 0.05515843 0.76225253]
 [0.52768776 0.60014448 0.15528928 0.61618398 0.31175971 0.38996526]
 [0.61610098 0.31185761 0.93636549 0.34267258 0.05060076 0.57715455]
 [0.1302083  0.29659634 0.41095929 0.60364572 0.27076651 0.55751436]] 
 Максимальне значення: 0.9363654910927465

Завдання 5:

Масив 1: [-3  5 -5 -3]
Масив 2: [ 0  4  5 -2]
Додавання: [-3  9  0 -5]
Віднімання: [ -3   1 -10  -1]
Множення: [  0  20 -25   6]

Завдання 6:

Вектор 1: [0.17719031 0.5091705  0.62819868 0.16474103]
Вектор 2: [0.80002369 0.61551232 0.